export const menuArray = [
  {
    name: "Pizza",
    ingredients: ["pepperoni", "mushrom", "mozarella"],
    id: 0,
    price: 14,
    emoji: "🍕",
  },
  {
    name: "Hamburger",
    ingredients: ["beef", "cheese", "lettuce"],
    price: 12,
    emoji: "🍔",
    id: 1,
  },
  {
    name: "Beer",
    ingredients: ["grain, hops, yeast, water"],
    price: 12,
    emoji: "🍺",
    id: 2,
  },
  {
    name: "Giant Tenderloin",
    ingredients: ["pork", "bun", "pickles"],
    price: 15,
    emoji: "🥪",
    id: 3,
  },
  {
    name: "Half a Giant Tenderloin",
    ingredients: ["pork", "bun", "pickles"],
    price: 8,
    emoji: "🥪",
    id: 4,
  },
  {
    name: "Breaded Cheeseburger",
    ingredients: ["beef", "cheese", "lettuce", "breading"],
    price: 10,
    emoji: "🍔",
    id: 5,
  },
  {
    name: "Chicken Strips",
    ingredients: ["chicken", "breading"],
    price: 10,
    emoji: "🍗",
    id: 6,
  },
  {
    name: "Hot Dog",
    ingredients: ["beef", "bun", "ketchup", "mustard"],
    price: 5,
    emoji: "🌭",
    id: 7,
  },
  {
    name: "Corn Dog",
    ingredients: ["beef", "bater", "stick"],
    price: 5,
    emoji: "🌽",
    id: 8,
  },
  {
    name: "French Fries",
    ingredients: ["potato", "salt"],
    price: 5,
    emoji: "🍟",
    id: 9,
  },
  {
    name: "Pepsi",
    ingredients: ["sugar", "water", "caramel color"],
    price: 3,
    emoji: "🥤",
    id: 10,
  },
  {
    name: "Diet Pepsi",
    ingredients: ["sugar", "water", "caramel color", "aspartame"],
    price: 3,
    emoji: "🥤",
    id: 11,
  },
  {
    name: "Dr. Pepper",
    ingredients: ["sugar", "water", "caramel color", "prune juice"],
    price: 3,
    emoji: "🥤",
    id: 12,
  },
  {
    name: "Mountain Dew",
    ingredients: ["sugar", "water", "caramel color", "caffeine!"],
    price: 3,
    emoji: "🥤",
    id: 13,
  },
  {
    name: "Starry",
    ingredients: ["sugar", "water", "lemon-lime flavor"],
    price: 3,
    emoji: "🥤",
    id: 14,
  },
];
